"""NPC encounter node for generating scene images.

This node generates an image for each turn of the encounter.
Uses the shared replicate_tool from examples/shared.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from examples.shared.replicate_tool import ImageResult, generate_image
from yamlgraph.contrib import to_serializable

logger = logging.getLogger(__name__)

# Type alias for state
GraphState = dict[str, Any]

# Output directory for generated images
OUTPUT_DIR = Path("outputs/npc/encounters")


def generate_scene_image_node(state: GraphState) -> dict:
    """Generate an image for the current encounter scene.

    Reads the scene_prompt from state (generated by describe_scene LLM node)
    and generates an image using the shared replicate tool.

    Args:
        state: Graph state with 'scene_prompt' containing the image prompt

    Returns:
        State update with 'scene_image' path and metadata
    """
    scene_prompt = state.get("scene_prompt")
    if not scene_prompt:
        logger.warning("No scene_prompt in state, skipping image generation")
        return {
            "current_step": "generate_scene_image",
            "scene_image": None,
        }

    # Handle Pydantic model or dict
    scene_data = to_serializable(scene_prompt)
    if isinstance(scene_data, dict):
        prompt_text = scene_data.get("prompt", str(scene_prompt))
    else:
        prompt_text = str(scene_prompt)

    # Add style suffix for consistent fantasy look
    style_suffix = (
        "Fantasy illustration style, dramatic lighting, "
        "detailed, vibrant colors, D&D inspired, painterly"
    )
    full_prompt = f"{prompt_text}. {style_suffix}"

    # Create output directory with timestamp
    turn_number = state.get("turn_number", 1)
    npc_name = state.get("npc_name", "unknown").replace(" ", "_").lower()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    output_dir = OUTPUT_DIR / f"{npc_name}_{timestamp}"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate image
    output_path = output_dir / f"turn_{turn_number:02d}.webp"

    logger.info(f"🎨 Generating scene image: {output_path}")
    logger.debug(f"Prompt: {full_prompt[:100]}...")

    result: ImageResult = generate_image(
        prompt=full_prompt,
        output_path=output_path,
        model_name="hidream",  # Better for fantasy/illustration style
    )

    if result.success:
        logger.info(f"✅ Generated image: {result.path}")
        return {
            "current_step": "generate_scene_image",
            "scene_image": str(result.path),
        }
    else:
        logger.error(f"❌ Image generation failed: {result.error}")
        return {
            "current_step": "generate_scene_image",
            "scene_image": None,
            "image_error": result.error,
        }
