"""TypedDict code generation from graph configuration (FR-008).

Extracted from state_builder (FR-797 module-size split); the runtime
TypedDict builder stays in state_builder — this module is the codegen
mirror and must synthesize the same fields.
"""

from pathlib import Path

from yamlgraph.models.relay_fields import (
    relay_codegen_fields,
    subgraph_relay_capable,
)

# Type mapping for code generation (YAML type -> Python type string)
CODEGEN_TYPE_MAP: dict[str, str] = {
    "str": "str",
    "string": "str",
    "int": "int",
    "integer": "int",
    "float": "float",
    "bool": "bool",
    "boolean": "bool",
    "list": "list",
    "dict": "dict",
    "any": "Any",
}


def _normalize_class_name(name: str) -> str:
    """Convert graph name to PascalCase class name.

    Examples:
        "interview" -> "Interview"
        "my-awesome-graph" -> "MyAwesomeGraph"
        "web_research" -> "WebResearch"
    """
    # Replace hyphens and underscores with spaces, then title-case
    normalized = name.replace("-", " ").replace("_", " ")
    return "".join(word.capitalize() for word in normalized.split())


def _codegen_state_fields(state_config: dict) -> dict[str, str]:
    """Extract code generation type strings from state config.

    Handles both simple string syntax and dict-syntax state definitions.
    """
    fields: dict[str, str] = {}
    for field_name, type_spec in state_config.items():
        if isinstance(type_spec, str):
            fields[field_name] = CODEGEN_TYPE_MAP.get(type_spec.lower(), "Any")
        elif isinstance(type_spec, dict):
            type_str = type_spec.get("type", "any")
            fields[field_name] = CODEGEN_TYPE_MAP.get(type_str.lower(), "Any")
    return fields


def generate_typeddict_code(
    config: dict,
    source_path: "str | Path | None" = None,
    include_base_fields: bool = False,
) -> str:
    """Generate TypedDict Python code from graph configuration.

    Args:
        config: Parsed YAML graph configuration dict
        source_path: Optional source file path for generation comment
        include_base_fields: Include infrastructure fields (thread_id, etc.)

    Returns:
        Python source code string defining the TypedDict
    """
    # Determine class name
    graph_name = config.get("name", "Graph")
    class_name = _normalize_class_name(graph_name) + "State"

    # Collect fields (custom state + node state_keys)
    fields: dict[str, str] = {}

    # Add base fields if requested
    if include_base_fields:
        fields["thread_id"] = "str"
        fields["current_step"] = "str"

        fields["errors"] = "list"
        fields["messages"] = "list"
        fields["_loop_counts"] = "dict"
        fields["_loop_limit_reached"] = "bool"
        fields["_agent_iterations"] = "int"
        fields["_agent_limit_reached"] = "bool"
        fields["started_at"] = "Any"
        fields["completed_at"] = "Any"

    # Parse custom state fields
    state_config = config.get("state", {})
    fields.update(_codegen_state_fields(state_config))

    # Extract fields from nodes
    nodes = config.get("nodes", {})
    for node_name, node_config in nodes.items():
        if not isinstance(node_config, dict):
            continue

        # state_key → Any
        if state_key := node_config.get("state_key"):
            fields[state_key] = "Any"

        # Node type-specific fields
        node_type = node_config.get("type", "llm")
        if node_type == "agent":
            fields["input"] = "str"
            fields["_tool_results"] = "list"
        elif node_type == "router":
            fields["_route"] = "str"
            # FR-272: router with candidates also emits _race_winner
            if node_config.get("candidates"):
                fields["_race_winner"] = "dict"
        elif node_type == "map":
            if collect_key := node_config.get("collect"):
                fields[collect_key] = "list"
        elif node_type == "race":
            fields["_race_winner"] = "dict"
        elif node_type == "subgraph" and subgraph_relay_capable(
            node_config, Path(source_path) if source_path else None
        ):
            # FR-797: relay internals for the two-node interrupt split
            fields.update(relay_codegen_fields(node_name))

    # Generate code
    lines = []

    # Header comment
    if source_path:
        lines.append(f"# Auto-generated by yamlgraph codegen from {source_path}")
    else:
        lines.append("# Auto-generated by yamlgraph codegen")
    lines.append(
        "# Do not edit manually - regenerate with: yamlgraph codegen <graph.yaml>"
    )
    lines.append("")

    # Imports
    lines.append("from typing import Any, TypedDict")
    lines.append("")
    lines.append("")

    # Class definition
    lines.append(f"class {class_name}(TypedDict, total=False):")
    lines.append(f'    """State for {graph_name} graph."""')
    lines.append("")

    # Fields
    if fields:
        for field_name, field_type in sorted(fields.items()):
            lines.append(f"    {field_name}: {field_type}")
    else:
        lines.append("    pass")

    lines.append("")
    return "\n".join(lines)
