stateDiagram-v2
    %% Detailed view of TERMINAL

    [*] --> completed
    [*] --> failed
    [*] --> stopped

    %% Internal transitions

    %% External composites
    state OPERATIONAL

    %% Transitions to other composites
