"""Email formatting node using Jinja2."""

import logging
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

logger = logging.getLogger(__name__)

# Template directory
TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

# Default template if file doesn't exist
DEFAULT_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Daily Tech Digest - {{ date }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; }
        h1 { color: #333; border-bottom: 2px solid #007acc; padding-bottom: 10px; }
        .story { margin-bottom: 20px; padding: 15px; background: #f9f9f9; border-radius: 5px; }
        .story h2 { margin: 0 0 10px 0; font-size: 1.1em; }
        .story h2 a { color: #007acc; text-decoration: none; }
        .story h2 a:hover { text-decoration: underline; }
        .story p { margin: 5px 0; color: #555; font-size: 0.9em; }
        .story .reason { font-style: italic; color: #888; }
        .empty { color: #666; font-style: italic; }
        footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 0.8em; }
    </style>
</head>
<body>
    <h1>🗞️ Daily Tech Digest</h1>
    <p><strong>{{ date }}</strong></p>

    {% if stories %}
    {% for story in stories %}
    <div class="story">
        <h2><a href="{{ story.url }}">{{ story.title }}</a></h2>
        {% if story.summary %}<p>{{ story.summary }}</p>{% endif %}
        {% if story.reason %}<p class="reason">Why: {{ story.reason }}</p>{% endif %}
    </div>
    {% endfor %}
    {% else %}
    <p class="empty">No stories found for today. Check back tomorrow!</p>
    {% endif %}

    <footer>
        <p>Generated by YAMLGraph Daily Digest</p>
    </footer>
</body>
</html>"""


def format_email(state: dict) -> dict:
    """Render HTML email using Jinja2 template."""
    today = state.get("today", "")
    ranked_stories = state.get("ranked_stories", [])

    # Handle Pydantic model response from LLM node
    if hasattr(ranked_stories, "stories"):
        ranked_stories = ranked_stories.stories
    # Convert Pydantic models to dicts if needed
    if ranked_stories and hasattr(ranked_stories[0], "model_dump"):
        ranked_stories = [s.model_dump() for s in ranked_stories]

    # Try to load template from file
    template_path = TEMPLATES_DIR / "digest.html"

    if template_path.exists():
        env = Environment(
            loader=FileSystemLoader(TEMPLATES_DIR),
            autoescape=select_autoescape(["html"]),
        )
        template = env.get_template("digest.html")
    else:
        # Use default embedded template
        env = Environment(autoescape=select_autoescape(["html"]))
        template = env.from_string(DEFAULT_TEMPLATE)

    html = template.render(date=today, stories=ranked_stories)

    logger.info(f"📧 Formatted email with {len(ranked_stories)} stories")
    return {"digest_html": html}
