#!/usr/bin/env python3
"""Generate CHANGELOG.md from changelog fragment files.

Usage:
    python scripts/aggregate_changelog.py > CHANGELOG.md

Reads changelog/unreleased/ and changelog/{version}/ directories.
Groups entries by type (Added/Fixed/Removed) in Keep a Changelog format.

Standalone script — requires PyYAML but no framework imports.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

# Section ordering: Keep a Changelog convention
SECTION_ORDER = ["Added", "Removed", "Fixed", "Changed", "Security"]
TYPE_TO_SECTION = {
    "feat": "Added",
    "fix": "Fixed",
    "removal": "Removed",
    "security": "Security",
}


@dataclass
class FragmentEntry:
    """A parsed changelog fragment."""

    entry_type: str
    scope: str | None
    req: str | None
    body: str
    fr_num: str | None

    @property
    def section(self) -> str:
        return TYPE_TO_SECTION.get(self.entry_type, "Changed")

    @property
    def sort_key(self) -> int:
        if self.fr_num:
            match = re.search(r"(\d+)$", self.fr_num)
            return int(match.group(1)) if match else 0
        return 0


def parse_fragment(filepath: Path) -> FragmentEntry:
    """Parse a changelog fragment file with YAML front matter."""
    content = filepath.read_text()
    if not content.startswith("---"):
        raise ValueError(f"Fragment {filepath} missing YAML front matter (---)")

    parts = content.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"Fragment {filepath} has incomplete front matter")

    front_matter = yaml.safe_load(parts[1])
    if not front_matter or "type" not in front_matter:
        raise ValueError(f"Fragment {filepath} missing required 'type' field")

    body = parts[2].strip()

    # Extract FR number from filename or body
    fr_match = re.search(r"(FR-\d+)", filepath.stem, re.IGNORECASE)
    if not fr_match:
        fr_match = re.search(r"\*\*(FR-\d+)", body)
    fr_num = fr_match.group(1).upper() if fr_match else None

    return FragmentEntry(
        entry_type=front_matter["type"],
        scope=front_matter.get("scope"),
        req=front_matter.get("req"),
        body=body,
        fr_num=fr_num,
    )


def aggregate(changelog_dir: Path) -> str:
    """Aggregate all fragments into a CHANGELOG.md string."""
    lines = ["<!-- Generated by aggregate_changelog.py -->", "", "# Changelog", ""]

    # Unreleased
    lines.append("## [Unreleased]")
    lines.append("")
    unreleased_dir = changelog_dir / "unreleased"
    if unreleased_dir.is_dir():
        _render_version_section(unreleased_dir, lines)

    # Versioned releases (sorted descending)
    versions = []
    for d in changelog_dir.iterdir():
        if d.is_dir() and d.name != "unreleased":
            versions.append(d.name)

    versions.sort(key=_version_sort_key, reverse=True)

    for version in versions:
        lines.append(f"## [{version}]")
        lines.append("")
        _render_version_section(changelog_dir / version, lines)

    return "\n".join(lines)


def _render_version_section(version_dir: Path, lines: list[str]) -> None:
    """Render all fragments in a version directory into grouped sections."""
    sections: dict[str, list[FragmentEntry]] = {}

    for fragment_path in sorted(version_dir.glob("*.md")):
        if fragment_path.name == ".gitkeep":
            continue
        try:
            entry = parse_fragment(fragment_path)
        except ValueError:
            continue
        sections.setdefault(entry.section, []).append(entry)

    for section_name in SECTION_ORDER:
        entries = sections.get(section_name, [])
        if not entries:
            continue
        # Sort by FR number descending (newest first)
        entries.sort(key=lambda e: e.sort_key, reverse=True)
        lines.append(f"### {section_name}")
        lines.append("")
        for entry in entries:
            lines.append(entry.body)
        lines.append("")


def _version_sort_key(version: str) -> tuple[int, ...]:
    """Sort version strings by numeric components."""
    parts = version.split(".")
    result = []
    for part in parts:
        try:
            result.append(int(part))
        except ValueError:
            result.append(0)
    return tuple(result)


def main() -> int:
    changelog_dir = REPO_ROOT / "changelog"
    if not changelog_dir.is_dir():
        print(f"ERROR: {changelog_dir} not found", file=sys.stderr)
        return 1

    output = aggregate(changelog_dir)
    print(output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
