"""Schemas for impl-agent discovery and planning.

These models define the structure for todo-driven discovery workflow.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class DiscoveryTask(BaseModel):
    """A single discovery task for impl-agent.

    Represents one investigation step in the discovery plan.
    """

    id: int = Field(description="Unique task identifier")
    task: str = Field(description="Human-readable description of what to discover")
    tool: str = Field(description="Name of the tool to call")
    args: dict[str, Any] = Field(description="Arguments to pass to the tool")
    rationale: str = Field(description="Why this discovery task matters")
    status: Literal["pending", "done", "failed"] = Field(
        default="pending",
        description="Current status of the task",
    )
    priority: int = Field(
        default=1,
        description="Priority (1=high, 2=medium, 3=low)",
        ge=1,
        le=3,
    )


class DiscoveryResult(BaseModel):
    """Result of executing a discovery task.

    Captures both successful results and error information.
    """

    task_id: int = Field(description="ID of the task that was executed")
    tool: str = Field(description="Name of the tool that was called")
    success: bool = Field(description="Whether the tool call succeeded")
    result: Any = Field(
        default=None,
        description="Result from the tool (if successful)",
    )
    error: str | None = Field(
        default=None,
        description="Error message (if failed)",
    )


class DiscoveryPlan(BaseModel):
    """Complete discovery plan with ordered tasks.

    Generated by the plan_discovery LLM node.
    """

    tasks: list[DiscoveryTask] = Field(
        default_factory=list,
        description="Ordered list of discovery tasks to execute",
    )


class DiscoveryFindings(BaseModel):
    """Accumulated discovery results.

    Collected by the execute_discovery map node.
    """

    results: list[DiscoveryResult] = Field(
        default_factory=list,
        description="Results from all executed discovery tasks",
    )
