#!/usr/bin/env python3
"""Generate CHANGELOG.md from changelog fragment files.

Usage:
    python scripts/aggregate_changelog.py [changelog_dir]

Reads all fragment files under changelog/, groups by version and type,
and emits a complete CHANGELOG.md to stdout.

Fragment format:
    ---
    type: feat|fix|removal
    scope: <scope>
    req: REQ-YG-XXX  (optional)
    ---
    - **FR-XXX Title**: Description. (REQ-YG-XXX)

FR-179: Append-Only Changelog Fragments
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CHANGELOG_DIR = REPO_ROOT / "changelog"

# Type → section heading
TYPE_SECTIONS: dict[str, str] = {
    "feat": "### Added",
    "fix": "### Fixed",
    "removal": "### Removed",
}

# Canonical section ordering (Keep a Changelog: Added → Removed → Fixed)
SECTION_ORDER = ["### Added", "### Removed", "### Fixed", "### Changed", "### Security"]


@dataclass
class ChangelogEntry:
    """A single changelog entry parsed from a fragment file."""

    fr_num: str
    entry_type: str
    scope: str
    req: str | None
    body: str
    sort_key: int  # numeric FR number for sorting


def parse_fragment(filepath: Path) -> ChangelogEntry:
    """Parse a changelog fragment file into a ChangelogEntry.

    Raises ValueError if required fields are missing.
    """
    content = filepath.read_text(encoding="utf-8")

    if not content.startswith("---"):
        raise ValueError(f"Fragment {filepath.name} missing YAML front matter")

    parts = content.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"Fragment {filepath.name} has malformed front matter")

    front_matter = yaml.safe_load(parts[1])
    if not front_matter or "type" not in front_matter:
        raise ValueError(
            f"Fragment {filepath.name} missing required 'type' field in front matter"
        )

    entry_type = front_matter["type"]
    if entry_type not in TYPE_SECTIONS:
        raise ValueError(
            f"Fragment {filepath.name} has unknown type '{entry_type}'. "
            f"Valid types: {list(TYPE_SECTIONS.keys())}"
        )

    scope = front_matter.get("scope", "")
    req = front_matter.get("req")
    body = parts[2].strip()

    # Extract FR number from filename or body
    fr_match = re.search(r"FR-(\d+)", filepath.name)
    if fr_match:
        fr_num = f"FR-{fr_match.group(1)}"
        sort_key = int(fr_match.group(1))
    else:
        # Try to extract from body
        body_match = re.search(r"FR-(\d+)", body)
        if body_match:
            fr_num = f"FR-{body_match.group(1)}"
            sort_key = int(body_match.group(1))
        else:
            fr_num = filepath.stem
            sort_key = 0

    return ChangelogEntry(
        fr_num=fr_num,
        entry_type=entry_type,
        scope=scope,
        req=req,
        body=body,
        sort_key=sort_key,
    )


def _parse_version_key(dirname: str) -> tuple[int, ...]:
    """Parse version string into sortable tuple. Higher = newer."""
    parts = dirname.split(".")
    try:
        return tuple(int(p) for p in parts)
    except ValueError:
        return (0,)


def _group_entries(entries: list[ChangelogEntry]) -> dict[str, list[ChangelogEntry]]:
    """Group entries by section heading, sorted by FR number descending."""
    groups: dict[str, list[ChangelogEntry]] = {}
    for entry in sorted(entries, key=lambda e: e.sort_key, reverse=True):
        section = TYPE_SECTIONS[entry.entry_type]
        groups.setdefault(section, []).append(entry)
    return groups


def _render_section(groups: dict[str, list[ChangelogEntry]]) -> list[str]:
    """Render grouped entries as markdown lines."""
    lines: list[str] = []
    for section in SECTION_ORDER:
        entries = groups.get(section, [])
        if entries:
            lines.append(section)
            for entry in entries:
                lines.append(entry.body)
            lines.append("")
    return lines


def aggregate(changelog_dir: Path) -> str:
    """Aggregate all changelog fragments into a complete CHANGELOG.md string."""
    lines: list[str] = []

    # Header
    lines.append(
        "<!-- Generated by scripts/aggregate_changelog.py — do not edit manually -->"
    )
    lines.append("# Changelog")
    lines.append("")
    lines.append("All notable changes to this project will be documented in this file.")
    lines.append("")
    lines.append(
        "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),"
    )
    lines.append(
        "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."
    )
    lines.append("")

    # Collect all version directories
    unreleased_dir = changelog_dir / "unreleased"
    version_dirs: list[tuple[str, Path]] = []

    for d in sorted(changelog_dir.iterdir()):
        if d.is_dir() and d.name != "unreleased":
            version_dirs.append((d.name, d))

    # Sort versions descending (newest first)
    version_dirs.sort(key=lambda vd: _parse_version_key(vd[0]), reverse=True)

    # Unreleased section
    lines.append("## [Unreleased]")
    lines.append("")
    if unreleased_dir.exists():
        fragments = list(unreleased_dir.glob("*.md"))
        if fragments:
            entries = []
            for f in fragments:
                try:
                    entries.append(parse_fragment(f))
                except ValueError as e:
                    print(f"WARNING: {e}", file=sys.stderr)
            groups = _group_entries(entries)
            lines.extend(_render_section(groups))

    # Versioned sections
    for version_name, version_path in version_dirs:
        lines.append(f"## [{version_name}]")
        lines.append("")
        fragments = list(version_path.glob("*.md"))
        if fragments:
            entries = []
            for f in fragments:
                try:
                    entries.append(parse_fragment(f))
                except ValueError as e:
                    print(f"WARNING: {e}", file=sys.stderr)
            groups = _group_entries(entries)
            lines.extend(_render_section(groups))

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    """Main entry point."""
    changelog_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CHANGELOG_DIR

    if not changelog_dir.exists():
        print(f"❌ Changelog directory not found: {changelog_dir}", file=sys.stderr)
        return 1

    output = aggregate(changelog_dir)
    print(output, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
