#!/usr/bin/env python3
"""FR-740: FR pipeline board — generated priority view + structural interrupts.

LLM-free reduce of existing ground truth (FR status headers, Parent
links, gates.yaml) into a priority table + Mermaid DAG. The board is
GENERATED; edits belong in the sources. `--check` is the two-way lint:
regenerate-and-diff, so a stale or hand-edited board fails pre-commit.

Judgement bindings (2026-07-16): active-set scoping (F1 — the 723-file
census forbids a 700-row board), status normalized at the boundary with
parse-failure rows never dropped (F2), .judgement.md companions
excluded (F3), gates.yaml is the gate source (F4), absent sibling repos
are a notice, never an error (F6).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HEADER = "<!-- GENERATED by scripts/fr_board.py — edit the sources, then regenerate -->"

STATUS_RE = re.compile(r"^\*\*Status:?\*\*:?\s*(.+)$", re.M)
PARENT_RE = re.compile(r"^\*\*Parent:\*\*\s*.*?\b((?:FR|NC)-\d{2,4})", re.M)
ID_RE = re.compile(r"^((?:FR|NC)-\d{2,4})")

# canonicalization map: known first tokens → canonical status (F2).
# Families beyond the census were added ONLY after the AC-06 read of the
# first real board measured them (198 parse failures → top families).
CANON = {
    "proposed": "Proposed",
    "judged": "Judged",
    "re-judged": "Judged",
    "rejudged": "Judged",
    "amended": "Judged",
    "amend": "Judged",
    "approved": "Approved",
    "granted": "Approved",
    "draft": "Draft",
    "in": "In Progress",
    "enforcing": "In Progress",
    "implemented": "Implemented",
    "enforced": "Enforced",
    "completed": "Completed",
    "complete": "Completed",
    "closed": "Completed",
    "✅": "Completed",
    "✓": "Completed",
    "done": "Completed",
    "rejected": "Rejected",
    "condemned": "Rejected",
    "❌": "Rejected",
    "superseded": "Superseded",
}
ACTIVE = {"Proposed", "Judged", "Approved", "In Progress", "Draft", "PARSE-FAILURE"}


def canonical_status(raw: str) -> str:
    words = raw.strip().split()
    token = words[0].strip("*,:;—-()").lower() if words else ""
    return CANON.get(token, "PARSE-FAILURE")


PYPROJECT_NAME_RE = re.compile(r'(?m)^name\s*=\s*"([^"]+)"')


def repo_display_name(repo: Path) -> str:
    """Stable repo identifier for the board's `repo` column.

    `repo.name` is the checkout directory's basename, which is wrong
    for git worktrees (e.g. `tmp/worktrees/fr-760` has dirname "fr-760",
    not the project name "yamlgraph") — regenerating the board from a
    worktree silently mislabels every row. Prefer `pyproject.toml`'s
    `[project].name`, which is identity-stable across worktrees; fall
    back to the directory name only when no pyproject.toml is present
    (e.g. a sibling repo in `--project` mode without one).
    """
    pyproject = repo / "pyproject.toml"
    if pyproject.is_file():
        match = PYPROJECT_NAME_RE.search(pyproject.read_text(errors="replace", encoding="utf-8"))
        if match:
            return match.group(1)
    return repo.name


def collect_rows(repo: Path) -> list[dict]:
    """Parse feature-requests/*.md into rows; companions and TEMPLATE excluded."""
    fr_dir = repo / "feature-requests"
    rows = []
    if not fr_dir.is_dir():
        return rows
    for path in sorted(fr_dir.glob("*.md")):
        if (
            ".judgement." in path.name
            or ".research." in path.name
            or path.name == "TEMPLATE.md"
        ):
            continue
        m_id = ID_RE.match(path.name)
        if not m_id:
            continue
        text = path.read_text(errors="replace", encoding="utf-8")
        m_status = STATUS_RE.search(text)
        raw = m_status.group(1).strip() if m_status else "(no Status header)"
        m_parent = PARENT_RE.search(text)
        rows.append(
            {
                "id": m_id.group(1),
                "file": path.name,
                "repo": repo_display_name(repo),
                "status": canonical_status(raw) if m_status else "PARSE-FAILURE",
                "raw": raw,
                "parent": m_parent.group(1) if m_parent else None,
            }
        )
    return rows


def active_rows(rows: list[dict]) -> list[dict]:
    """F1: the board's default subject is FRs in motion."""
    return [r for r in rows if r["status"] in ACTIVE]


def validate_gates(gates: list[dict]) -> list[str]:
    """AC-03: an OPEN gate without owner/ask_by/question is a lint failure."""
    errors = []
    for g in gates:
        gid = g.get("id", "?")
        if g.get("status") != "open":
            continue
        for field in ("owner", "ask_by"):
            if not g.get(field):
                errors.append(f"gate {gid}: missing {field}")
        q = g.get("question")
        if not (isinstance(q, dict) and q.get("text") and q.get("options")):
            errors.append(f"gate {gid}: missing question block (text+options)")
    return errors


def load_gates(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    import yaml

    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data.get("gates", [])


def render_board(
    repos: list[Path], gates: list[dict] | None = None, all_rows: bool = False
) -> str:
    gates = gates or []
    lines = [HEADER, "", "# FR Pipeline Board", ""]
    rows: list[dict] = []
    for repo in repos:
        if not (repo / "feature-requests").is_dir():
            lines.append(f"> note: skipped missing repo: {repo.name}")
            continue
        rows.extend(collect_rows(repo))
    shown = rows if all_rows else active_rows(rows)
    gate_by_fr: dict[str, list[str]] = {}
    for g in gates:
        gate_by_fr.setdefault(g.get("fr", "?"), []).append(
            f"{g.get('id')}({g.get('status')})"
        )
    lines += [
        "",
        "| FR | status | repo | gates | file |",
        "|----|--------|------|-------|------|",
    ]
    order = {
        "PARSE-FAILURE": 0,
        "Judged": 1,
        "Approved": 2,
        "Proposed": 3,
        "In Progress": 4,
        "Draft": 5,
    }
    for r in sorted(shown, key=lambda r: (order.get(r["status"], 9), r["id"])):
        status = (
            r["status"]
            if r["status"] != "PARSE-FAILURE"
            else f"PARSE-FAILURE ({r['raw'][:30]})"
        )
        lines.append(
            f"| {r['id']} | {status} | {r['repo']} |"
            f" {', '.join(gate_by_fr.get(r['id'], []))} | {r['file']} |"
        )
    lines += ["", "```mermaid", "graph TD"]
    shown_ids = {r["id"] for r in shown}
    for r in shown:
        lines.append(f'    {r["id"]}["{r["id"]} {r["status"]}"]')
    for r in shown:
        if r["parent"] and r["parent"] in shown_ids | {row["id"] for row in rows}:
            lines.append(f"    {r['parent']} --> {r['id']}")
    for g in gates:
        if g.get("fr") in shown_ids:
            lines.append(
                f"    {g.get('id')}{{{{gate {g.get('id')} {g.get('status')}}}}} --> {g['fr']}"
            )
    lines += ["```", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Render the FR pipeline board to stdout (FR-858: query only)."
    )
    ap.add_argument(
        "--project",
        action="append",
        default=[],
        help="sibling repo for the EPHEMERAL stdout view; never written or"
        " checked (F7: each repo owns its board — committed state must not"
        " embed another repo's working tree)",
    )
    ap.add_argument("--gates", default="feature-requests/gates.yaml")
    ap.add_argument("--all", action="store_true", help="include terminal statuses")
    args = ap.parse_args()

    own = [Path.cwd()]
    gates = load_gates(Path(args.gates))

    if args.project:  # F7: cross-repo aggregate is a terminal view, like now.py
        print(render_board(own + [Path(p) for p in args.project], gates, args.all))
        return 0

    errors = validate_gates(gates)
    if errors:
        for e in errors:
            print(f"✗ {e}")
        return 1
    print(render_board(own, gates, all_rows=args.all))
    return 0


if __name__ == "__main__":
    sys.exit(main())
