#!/usr/bin/env python3
"""MCP Sampling Loopback PoC — prove the server can talk back to Copilot.

This MCP server exposes a single tool: ``loopback_pray``.
When invoked, it sends a ``sampling/createMessage`` request BACK to the
connected MCP client (VS Code Copilot), asking it to respond to
"Let us pray". The client's LLM generates a response — no API key needed
on the server side.

Usage:
    Configure in .vscode/mcp.json, then ask Copilot to use the loopback_pray tool.

Protocol flow:
    1. Copilot calls ``loopback_pray`` tool
    2. Server sends ``sampling/createMessage`` with "Let us pray"
    3. Copilot's LLM generates a prayer
    4. Server returns the prayer as the tool result
"""

from __future__ import annotations

import asyncio
import json
import logging
import sys

import mcp.server.stdio
import mcp.types as types
from mcp.server.lowlevel.server import NotificationOptions, Server
from mcp.server.models import InitializationOptions

logging.basicConfig(level=logging.INFO, stream=sys.stderr)
logger = logging.getLogger("loopback-poc")

server = Server("loopback-poc")


@server.list_tools()
async def handle_list_tools() -> list[types.Tool]:
    """Expose the loopback_pray tool."""
    return [
        types.Tool(
            name="loopback_pray",
            description=(
                "Sends 'Let us pray' back to the connected AI assistant via "
                "MCP Sampling. The assistant's own LLM generates the response. "
                "No API keys used on the server side. "
                "This is a proof-of-concept for bidirectional MCP communication."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "Optional custom prompt (default: 'Let us pray')",
                    },
                },
            },
        ),
    ]


@server.call_tool()
async def handle_call_tool(name: str, arguments: dict) -> list[types.TextContent]:
    """Handle tool calls — the magic happens here."""
    if name != "loopback_pray":
        return [
            types.TextContent(
                type="text", text=json.dumps({"error": f"Unknown tool: {name}"})
            )
        ]

    prompt = arguments.get("prompt", "Let us pray")
    logger.info("Loopback PoC: sending sampling request to client: %r", prompt)

    # --- THE KEY PART: Call back to the connected AI assistant ---
    try:
        ctx = server.request_context
        session = ctx.session

        result = await session.create_message(
            messages=[
                types.SamplingMessage(
                    role="user",
                    content=types.TextContent(type="text", text=prompt),
                )
            ],
            max_tokens=500,
            system_prompt=(
                "You are a chaplain of software engineering. "
                "Respond to the prayer request in the spirit of the YAMLGraph Scripture. "
                "Keep it concise but inspiring."
            ),
        )

        # Extract the response text
        if isinstance(result.content, types.TextContent) or hasattr(
            result.content, "text"
        ):
            response_text = result.content.text
        else:
            response_text = str(result.content)

        model_used = getattr(result, "model", "unknown")
        stop_reason = getattr(result, "stopReason", "unknown")

        logger.info(
            "Loopback PoC: received response from client LLM (model=%s, stop=%s)",
            model_used,
            stop_reason,
        )

        return [
            types.TextContent(
                type="text",
                text=json.dumps(
                    {
                        "status": "success",
                        "prompt_sent": prompt,
                        "response": response_text,
                        "model": model_used,
                        "stop_reason": stop_reason,
                        "note": (
                            "This response was generated by the connected AI assistant "
                            "via MCP Sampling — no API key was used on the server side."
                        ),
                    },
                    indent=2,
                ),
            )
        ]

    except Exception as e:
        logger.error("Loopback PoC: sampling failed: %s", e, exc_info=True)
        return [
            types.TextContent(
                type="text",
                text=json.dumps(
                    {
                        "status": "error",
                        "error": str(e),
                        "error_type": type(e).__name__,
                        "hint": (
                            "Ensure the MCP client supports sampling. "
                            "VS Code Copilot supports it — enable YOLO mode "
                            "(chat.tools.global.autoApprove) for auto-consent."
                        ),
                    },
                    indent=2,
                ),
            )
        ]


async def main() -> None:
    """Run the loopback PoC MCP server."""
    logger.info("Starting Loopback PoC MCP server (stdio transport)...")

    async with mcp.server.stdio.stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="loopback-poc",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
