"""Integration tests for SIM117 (nested with statements) auto-fixing.

Tests that ruff --unsafe-fixes can automatically combine nested with statements
in real scenarios that might be generated by copilot nodes.
"""

import tempfile
from pathlib import Path
import subprocess
import pytest


@pytest.mark.req("REQ-YG-287")
class TestSIM117AutoFix:
    """Tests for SIM117 auto-fixing with --unsafe-fixes flag."""

    def test_nested_with_statements_auto_fix(self):
        """Test that ruff --unsafe-fixes can fix SIM117 violations."""
        # Create a temporary Python file with nested with statements
        problematic_code = '''
with open("file1.txt") as f1:
    with open("file2.txt") as f2:
        content = f1.read() + f2.read()
        print(content)
'''
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
            f.write(problematic_code)
            temp_file = Path(f.name)
        
        try:
            # Run ruff check with --unsafe-fixes to fix SIM117
            result = subprocess.run(
                ["ruff", "check", "--fix", "--unsafe-fixes", str(temp_file)],
                capture_output=True,
                text=True
            )
            
            # Read the fixed content
            fixed_content = temp_file.read_text()
            
            # Verify SIM117 fix was applied
            assert "with open(\"file1.txt\") as f1, open(\"file2.txt\") as f2:" in fixed_content
            assert fixed_content.count("with ") == 1, "Should combine into single with statement"
            
        finally:
            temp_file.unlink()

    def test_ruff_unsafe_fixes_flag_available(self):
        """Test that ruff supports the --unsafe-fixes flag."""
        result = subprocess.run(
            ["ruff", "check", "--help"],
            capture_output=True,
            text=True
        )
        
        assert "--unsafe-fixes" in result.stdout, "ruff should support --unsafe-fixes flag"